# Generated by Django 4.2.2 on 2023-06-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
